
# Reference: https://nodejs.org/en/docs/guides/nodejs-docker-webapp/
#			 

FROM node:16

# Create working directory in the container (source will be stored there)
WORKDIR /var/websocket-to-pubsub-ingest

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

# Nothing to expose
#EXPOSE 8080

ENTRYPOINT [ "node", "subscribeToMarketChannel.js" ]

